---
name: notes_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  font_awesome_flutter: ^10.5.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
    - asset: lib/assets/fonts/poppins-Regular.ttf
      style: italic
